# Generated by Django 5.1.6 on 2025-03-08 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cover',
            field=models.ImageField(default='courses_covers/default.jpg', upload_to='courses_covers/'),
        ),
    ]
