# Generated by Django 5.1.6 on 2025-03-08 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(default='python-basics', unique=True),
            preserve_default=False,
        ),
    ]
