# Generated by Django 5.1.6 on 2025-03-09 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.SmallIntegerField(default=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='skill_requirements',
            field=models.TextField(default=6),
            preserve_default=False,
        ),
    ]
