# Generated by Django 5.1.6 on 2025-04-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_enrollment_unique_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='count_lessons',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enrollment',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
