# Generated by Django 5.1.6 on 2025-04-17 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_course_count_lessons_enrollment_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='count_lessons',
        ),
        migrations.AddField(
            model_name='course',
            name='total_points',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
