# Generated by Django 5.1.6 on 2025-04-19 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_remove_course_count_lessons_course_total_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tags',
            field=models.CharField(blank=True, choices=[('Python', 'Python'), ('Django', 'Django'), ('FastAPI', 'FastAPI'), ('SQL', 'SQL'), ('JavaScript', 'JavaScript')], max_length=32),
        ),
    ]
