# Generated by Django 5.1.6 on 2025-04-20 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_coursetag_remove_course_tags_course_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='courses', to='courses.coursetag'),
        ),
    ]
