# Generated by Django 5.1.6 on 2025-03-08 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('lessons', '0001_initial'),
        ('tasks', '0002_remove_choicetask_title_remove_codetask_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='codetask',
            name='default_code',
            field=models.CharField(default=0, max_length=1024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='codetask',
            name='correct_code',
            field=models.CharField(max_length=1024),
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.PositiveIntegerField()),
                ('answer', models.JSONField()),
                ('completed', models.BooleanField(default=False)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='lessons.lesson')),
                ('task_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
