# Generated by Django 5.1.6 on 2025-03-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_codetask_default_code_alter_codetask_correct_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codetask',
            name='default_code',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
