# Generated by Django 5.1.6 on 2025-03-29 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_lesson_unique_lesson_position'),
        ('tasks', '0004_alter_codetask_default_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='task_type',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='user',
        ),
        migrations.RemoveField(
            model_name='choicetask',
            name='choices',
        ),
        migrations.AddField(
            model_name='choicetask',
            name='question_type',
            field=models.CharField(choices=[('SINGLE', 'Single Choice'), ('MULTIPLE', 'Multiple Choice')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='choicetask',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.lesson'),
        ),
        migrations.AlterField(
            model_name='choicetask',
            name='question',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('choice_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='tasks.choicetask')),
            ],
        ),
        migrations.CreateModel(
            name='UserChoiceAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.choicetask')),
                ('selected_answers', models.ManyToManyField(to='tasks.answer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CodeTask',
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
