# Generated by Django 5.1.6 on 2025-03-31 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_remove_submission_lesson_remove_submission_task_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userchoiceanswer',
            name='is_correct',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='choicetask',
            name='question',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='userchoiceanswer',
            name='choice_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_choice_answers', to='tasks.choicetask'),
        ),
        migrations.AlterField(
            model_name='userchoiceanswer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_choice_answers', to=settings.AUTH_USER_MODEL),
        ),
    ]
