# Generated by Django 5.1.6 on 2025-04-04 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_lesson_unique_lesson_position'),
        ('tasks', '0006_userchoiceanswer_is_correct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choicetask',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='lessons.lesson'),
        ),
    ]
