# Generated by Django 5.1.6 on 2025-04-17 13:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_choicetask_lesson'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userchoiceanswer',
            constraint=models.UniqueConstraint(fields=('user', 'choice_task'), name='unique_user_choice_answer'),
        ),
    ]
