# Generated by Django 5.1.6 on 2025-04-17 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_rename_count_tasks_lesson_total_points'),
        ('tasks', '0008_userchoiceanswer_unique_user_choice_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='choicetask',
            name='points',
            field=models.SmallIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='choicetask',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice_tasks', to='lessons.lesson'),
        ),
    ]
