# Generated by Django 5.1.6 on 2025-04-17 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_choicetask_points_alter_choicetask_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choicetask',
            name='question_type',
        ),
    ]
