# Generated by Django 5.1.6 on 2025-04-17 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_remove_choicetask_question_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userchoiceanswer',
            name='is_correct',
        ),
        migrations.AddField(
            model_name='userchoiceanswer',
            name='points',
            field=models.SmallIntegerField(default=0),
        ),
    ]
