# Generated by Django 5.1.6 on 2025-04-20 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_remove_userchoiceanswer_is_correct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchoiceanswer',
            name='selected_answers',
            field=models.ManyToManyField(related_name='user_choice_answers', to='tasks.answer'),
        ),
    ]
