# Generated by Django 5.1.6 on 2025-03-09 11:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_alter_lesson_course'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='user_lesson_complete',
            field=models.ManyToManyField(related_name='user_lesson_complete', to=settings.AUTH_USER_MODEL),
        ),
    ]
