# Generated by Django 5.1.6 on 2025-04-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_lesson_unique_lesson_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='count_tasks',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
