# Generated by Django 5.1.6 on 2025-04-17 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_lesson_count_tasks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='count_tasks',
            new_name='total_points',
        ),
    ]
