# Generated by Django 5.1.6 on 2025-04-17 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_rename_count_tasks_lesson_total_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='position',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='total_points',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
