# Generated by Django 5.1.6 on 2025-04-19 09:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0007_alter_lesson_position_alter_lesson_total_points'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='user_lesson_complete',
            field=models.ManyToManyField(blank=True, related_name='user_lesson_complete', to=settings.AUTH_USER_MODEL),
        ),
    ]
