# Generated by Django 5.1.6 on 2025-04-20 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0008_alter_lesson_user_lesson_complete'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Text', 'Text'), ('Code', 'Code')], max_length=20)),
                ('content', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='lessons.lessoncontent'),
        ),
    ]
