# Generated by Django 5.1.6 on 2025-04-20 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0009_lessoncontent_alter_lesson_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='content',
        ),
        migrations.AddField(
            model_name='lesson',
            name='content',
            field=models.ManyToManyField(related_name='lessons', to='lessons.lessoncontent'),
        ),
    ]
